wucdbm_banner_dashboard:
    path:        /
    defaults:    { _controller: Wucdbm\Bundle\BannerBundle\Controller\DashboardController::dashboardAction }

wucdbm_banner_banner:
    resource: routing/banner.yml
    prefix: /banners

wucdbm_banner_banner_choice:
    resource: routing/banner_choice.yml
    prefix: /banners/choice

wucdbm_banner_banner_position:
    resource: routing/banner_position.yml
    prefix: /banners/positions