wucdbm_banner_choice_choose:
      path:      /positions/choose
      defaults:  { _controller: WucdbmBannerBundle:BannerChoice:choose }

wucdbm_banner_choice_update_banner:
      path:      /positions/{id}/update/banner
      defaults:  { _controller: WucdbmBannerBundle:BannerChoice:updatePositionBanner }