wucdbm_banner_banner_list:
      path:      /list
      defaults:  { _controller: WucdbmBannerBundle:Banner:list }

wucdbm_banner_banner_edit:
      path:      /{id}/edit
      defaults:  { _controller: WucdbmBannerBundle:Banner:edit }

wucdbm_banner_banner_create:
      path:      /new
      defaults:  { _controller: WucdbmBannerBundle:Banner:create }

wucdbm_banner_banner_preview:
      path:      /{id}/preview
      defaults:  { _controller: WucdbmBannerBundle:Banner:preview }

wucdbm_banner_banner_activate:
      path:      /{id}/activate
      defaults:  { _controller: WucdbmBannerBundle:Banner:activate }

wucdbm_banner_banner_deactivate:
      path:      /{id}/deactivate
      defaults:  { _controller: WucdbmBannerBundle:Banner:deactivate }

wucdbm_banner_banner_refresh:
      path:      /{id}/refresh
      defaults:  { _controller: WucdbmBannerBundle:Banner:refresh }

wucdbm_banner_banner_delete:
      path:      /{id}/delete
      defaults:  { _controller: WucdbmBannerBundle:Banner:delete }