wucdbm_banner_position_list:
      path:      /list
      defaults:  { _controller: WucdbmBannerBundle:BannerPosition:list }

wucdbm_banner_position_edit:
      path:      /{id}/edit
      defaults:  { _controller: WucdbmBannerBundle:BannerPosition:edit }

wucdbm_banner_position_create:
      path:      /new
      defaults:  { _controller: WucdbmBannerBundle:BannerPosition:create }

wucdbm_banner_position_activate:
      path:      /{id}/activate
      defaults:  { _controller: WucdbmBannerBundle:BannerPosition:activate }

wucdbm_banner_position_deactivate:
      path:      /{id}/deactivate
      defaults:  { _controller: WucdbmBannerBundle:BannerPosition:deactivate }

wucdbm_banner_position_refresh:
      path:      /{id}/refresh
      defaults:  { _controller: WucdbmBannerBundle:BannerPosition:refresh }

wucdbm_banner_position_delete:
      path:      /{id}/delete
      defaults:  { _controller: WucdbmBannerBundle:BannerPosition:delete }